"""add reviews access to user_access

Revision ID: 012e76eb8002
Revises: 7d697fdcd01a
Create Date: 2025-09-17 16:52:22.800861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012e76eb8002'
down_revision = '7d697fdcd01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviews', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_access', schema=None) as batch_op:
        batch_op.drop_column('reviews')

    # ### end Alembic commands ###
