"""Add department_slug to Doctor model

Revision ID: 01659e1c4d6a
Revises: 1b9ffb8a81a3
Create Date: 2025-09-13 12:16:31.931231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01659e1c4d6a'
down_revision = '1b9ffb8a81a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_slug', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('department_slug')

    # ### end Alembic commands ###
