"""add guides to user_access

Revision ID: 0e3bfb498ad4
Revises: e3b13fd5046a
Create Date: 2026-02-25 14:39:47.651841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3bfb498ad4'
down_revision = 'e3b13fd5046a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guides', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_access', schema=None) as batch_op:
        batch_op.drop_column('guides')

    # ### end Alembic commands ###
