"""Add specialists_heading and specialists_content to departments

Revision ID: 195ab4aacd14
Revises: 2ea7196f89c8
Create Date: 2025-10-11 10:56:37.010440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195ab4aacd14'
down_revision = '2ea7196f89c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialists_heading', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('specialists_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('specialists_content')
        batch_op.drop_column('specialists_heading')

    # ### end Alembic commands ###
