"""Add structured timings to doctors table

Revision ID: 1b9ffb8a81a3
Revises: 22432964fba6
Create Date: 2025-09-13 11:55:12.744085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9ffb8a81a3'
down_revision = '22432964fba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_from', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('day_to', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('time_from_hour', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('time_from_min', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('time_from_ampm', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('time_to_hour', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('time_to_min', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('time_to_ampm', sa.String(length=2), nullable=True))
        batch_op.drop_column('timings')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timings', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('time_to_ampm')
        batch_op.drop_column('time_to_min')
        batch_op.drop_column('time_to_hour')
        batch_op.drop_column('time_from_ampm')
        batch_op.drop_column('time_from_min')
        batch_op.drop_column('time_from_hour')
        batch_op.drop_column('day_to')
        batch_op.drop_column('day_from')

    # ### end Alembic commands ###
