"""Add blogs and bmw_report columns to user_access

Revision ID: 1ba0a7d53450
Revises: 012e76eb8002
Create Date: 2025-10-08 10:54:03.510506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba0a7d53450'
down_revision = '012e76eb8002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blogs', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bmw_report', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_access', schema=None) as batch_op:
        batch_op.drop_column('bmw_report')
        batch_op.drop_column('blogs')

    # ### end Alembic commands ###
