"""Changes in Testimonials

Revision ID: 1ba64a6a1f59
Revises: 878163a02b8b
Create Date: 2025-11-17 10:12:39.675772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba64a6a1f59'
down_revision = '878163a02b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('doctor2_id', sa.Integer(), nullable=True))
        batch_op.alter_column('doctor_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.create_foreign_key(
            'fk_testimonial_doctor2_id', 'doctors', ['doctor2_id'], ['id'])
        batch_op.drop_column('patient_image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_image_path',
                            sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_constraint(
            'fk_testimonial_doctor2_id', type_='foreignkey')
        batch_op.alter_column('doctor_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.drop_column('doctor2_id')

    # ### end Alembic commands ###
