"""Add doctor_name to LifeMoment

Revision ID: 1d4891c3cc7d
Revises: 451ac5546158
Create Date: 2025-12-12 16:42:42.323132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4891c3cc7d'
down_revision = '451ac5546158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('life_moments', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('doctor_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('life_moments', schema=None) as batch_op:
        batch_op.drop_column('doctor_name')

    # ### end Alembic commands ###
