"""Initial migration

Revision ID: 22432964fba6
Revises: a7017ac1a519
Create Date: 2025-09-13 11:16:47.397860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22432964fba6'
down_revision = 'a7017ac1a519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
