"""add fellowship_links fellowship_file_path talks_links talks_file_path to doctors table

Revision ID: 22f866fb10f0
Revises: 892debeb0a81
Create Date: 2025-09-16 10:06:45.506364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f866fb10f0'
down_revision = '892debeb0a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fellowship_links', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fellowship_file_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('talks_links', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('talks_file_path', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('talks_file_path')
        batch_op.drop_column('talks_links')
        batch_op.drop_column('fellowship_file_path')
        batch_op.drop_column('fellowship_links')

    # ### end Alembic commands ###
