"""Add callback_requests column to UserAccess

Revision ID: 2885c354cfbd
Revises: 5c02717c7056
Create Date: 2025-09-17 13:07:28.369879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2885c354cfbd'
down_revision = '5c02717c7056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('callback_requests', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('callback_requests')

    # ### end Alembic commands ###
