"""Add appointment_link column to Doctor

Revision ID: 28d82166994a
Revises: 5390de35595a
Create Date: 2025-09-10 13:16:25.319663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d82166994a'
down_revision = '5390de35595a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_link', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('appointment_link')

    # ### end Alembic commands ###
