"""Remove position and company columns

Revision ID: 2ea7196f89c8
Revises: 98dbc5dbdfd1
Create Date: 2025-10-10 15:53:37.733325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea7196f89c8'
down_revision = '98dbc5dbdfd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_testimonials', schema=None) as batch_op:
        batch_op.drop_column('position')
        batch_op.drop_column('company')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_testimonials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('position', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
