"""Add display_order field to doctors table

Revision ID: 30ebf89c2cd5
Revises: 5772cb591d8b
Create Date: 2025-10-09 16:48:35.011302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ebf89c2cd5'
down_revision = '5772cb591d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
