"""initial migration

Revision ID: 38a9d9eef959
Revises: f075fc41d646
Create Date: 2025-12-12 11:02:24.924462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a9d9eef959'
down_revision = 'f075fc41d646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_link', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.drop_column('youtube_link')

    # ### end Alembic commands ###
