"""Remove position_class from Banner

Revision ID: 3b00d38ea650
Revises: b762257716c8
Create Date: 2025-09-15 09:30:16.731529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b00d38ea650'
down_revision = 'b762257716c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.drop_column('position_class')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('overview_content')
        batch_op.drop_column('overview_quote_author')
        batch_op.drop_column('overview_quote')
        batch_op.drop_column('services')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('overview_quote', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('overview_quote_author', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('overview_content', sa.TEXT(), nullable=True))

    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_class', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
