"""Changes in Testimonials

Revision ID: 4368defe1c3d
Revises: 1ba64a6a1f59
Create Date: 2025-11-18 11:42:50.092597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4368defe1c3d'
down_revision = '1ba64a6a1f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('canonical_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('canonical_url')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')

    # ### end Alembic commands ###
