"""initial migration

Revision ID: 451ac5546158
Revises: 38a9d9eef959
Create Date: 2025-12-12 13:29:15.631427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451ac5546158'
down_revision = '38a9d9eef959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('life_moments', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_access', schema=None) as batch_op:
        batch_op.drop_column('life_moments')

    # ### end Alembic commands ###
