"""Rename services_content to services_overview in department_services

Revision ID: 4aac4f7bc0e6
Revises: 652cc4f7a63a
Create Date: 2025-10-11 12:09:01.676411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aac4f7bc0e6'
down_revision = '652cc4f7a63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services_overview', sa.Text(), nullable=True))
        batch_op.drop_column('services_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services_content', sa.TEXT(), nullable=True))
        batch_op.drop_column('services_overview')

    # ### end Alembic commands ###
