"""Added qualification, overview, fellowship, expertise, talks fields to Doctor

Revision ID: 5390de35595a
Revises: cc49c341a82f
Create Date: 2025-09-10 10:08:04.508593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5390de35595a'
down_revision = 'cc49c341a82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_doctors')
    op.drop_table('health_package')
    op.drop_table('department_pages')
    op.drop_table('department_doctor')
    op.drop_table('healthpackage')
    op.drop_table('doctor')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('overview', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fellowship_membership', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('field_of_expertise', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('talks_and_publications', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('talks_and_publications')
        batch_op.drop_column('field_of_expertise')
        batch_op.drop_column('fellowship_membership')
        batch_op.drop_column('overview')
        batch_op.drop_column('qualification')

    op.create_table('doctor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=200), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('healthpackage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('tests', sa.TEXT(), nullable=True),
    sa.Column('original_price', sa.VARCHAR(length=50), nullable=True),
    sa.Column('offer_price', sa.VARCHAR(length=50), nullable=True),
    sa.Column('discount', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_doctor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=100), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=200), nullable=True),
    sa.Column('languages', sa.TEXT(), nullable=True),
    sa.Column('consultation_hours', sa.TEXT(), nullable=True),
    sa.Column('appointment_link', sa.VARCHAR(length=200), nullable=True),
    sa.Column('department_slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('department_pages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), nullable=False),
    sa.Column('banner_image', sa.VARCHAR(length=300), nullable=True),
    sa.Column('banner_alt_text', sa.VARCHAR(length=200), nullable=True),
    sa.Column('banner_title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('banner_subtitle', sa.VARCHAR(length=300), nullable=True),
    sa.Column('quote_text', sa.TEXT(), nullable=True),
    sa.Column('quote_author', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('services', sa.TEXT(), nullable=True),
    sa.Column('doctors', sa.TEXT(), nullable=True),
    sa.Column('meta_description', sa.TEXT(), nullable=True),
    sa.Column('meta_keywords', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('health_package',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('tests', sa.TEXT(), nullable=True),
    sa.Column('original_price', sa.VARCHAR(length=50), nullable=True),
    sa.Column('offer_price', sa.VARCHAR(length=50), nullable=True),
    sa.Column('discount', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_doctors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=300), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('languages', sa.TEXT(), nullable=True),
    sa.Column('consultation_hours', sa.TEXT(), nullable=True),
    sa.Column('appointment_link', sa.VARCHAR(length=500), nullable=True),
    sa.Column('department_slug', sa.VARCHAR(length=200), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
