"""Remove author and read_time from Blog

Revision ID: 5772cb591d8b
Revises: 1ba0a7d53450
Create Date: 2025-10-08 14:39:18.534313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5772cb591d8b'
down_revision = '1ba0a7d53450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('author')
        batch_op.drop_column('read_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_time', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
