"""Add callback_requests table

Revision ID: 5c02717c7056
Revises: f2cd24ea4ee3
Create Date: 2025-09-17 12:57:12.400261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c02717c7056'
down_revision = 'f2cd24ea4ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('timings',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('timings',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###
