"""Add banner_alt_text to Department

Revision ID: 5e2e5ba22584
Revises: 4aac4f7bc0e6
Create Date: 2025-10-17 16:01:34.664140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2e5ba22584'
down_revision = '4aac4f7bc0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_alt_text', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('banner_alt_text')

    # ### end Alembic commands ###
