"""Add services_content to department_services

Revision ID: 652cc4f7a63a
Revises: 195ab4aacd14
Create Date: 2025-10-11 11:55:05.405756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652cc4f7a63a'
down_revision = '195ab4aacd14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_services', schema=None) as batch_op:
        batch_op.drop_column('services_content')

    # ### end Alembic commands ###
