"""Move callback_requests from users to user_access

Revision ID: 7d697fdcd01a
Revises: 2885c354cfbd
Create Date: 2025-09-17 13:12:55.259725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d697fdcd01a'
down_revision = '2885c354cfbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('callback_requests', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('callback_requests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('callback_requests', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('user_access', schema=None) as batch_op:
        batch_op.drop_column('callback_requests')

    # ### end Alembic commands ###
