"""Add User and UserAccess tables

Revision ID: 892debeb0a81
Revises: f131bb78f73a
Create Date: 2025-09-15 13:00:22.804219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892debeb0a81'
down_revision = 'f131bb78f73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('emp_id')
    )
    op.create_table('user_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('banners', sa.Boolean(), nullable=True),
    sa.Column('doctors', sa.Boolean(), nullable=True),
    sa.Column('counters', sa.Boolean(), nullable=True),
    sa.Column('testimonials', sa.Boolean(), nullable=True),
    sa.Column('specialities', sa.Boolean(), nullable=True),
    sa.Column('departments', sa.Boolean(), nullable=True),
    sa.Column('health_packages', sa.Boolean(), nullable=True),
    sa.Column('sports_packages', sa.Boolean(), nullable=True),
    sa.Column('department_content', sa.Boolean(), nullable=True),
    sa.Column('users', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_access')
    op.drop_table('users')
    # ### end Alembic commands ###
