"""add dynamic content fields to departmentnew

Revision ID: a1b2c3d4e5f6
Revises: 012e76eb8002
Create Date: 2025-03-16 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '0e3bfb498ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_new', schema=None) as batch_op:
        # Hero Section fields
        batch_op.add_column(sa.Column('hero_main_heading', sa.String(500), nullable=True))
        batch_op.add_column(sa.Column('hero_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hero_phone', sa.String(20), nullable=True))
        batch_op.add_column(sa.Column('hero_stats', sa.Text(), nullable=True))
        
        # Overview Section fields
        batch_op.add_column(sa.Column('overview_heading', sa.String(300), nullable=True))
        batch_op.add_column(sa.Column('overview_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('why_choose_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('why_choose_items', sa.Text(), nullable=True))
        
        # Approach Section fields
        batch_op.add_column(sa.Column('approach_heading', sa.String(300), nullable=True))
        batch_op.add_column(sa.Column('approach_subheading', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('approach_cards', sa.Text(), nullable=True))
        
        # Services Section fields
        batch_op.add_column(sa.Column('services_heading', sa.String(300), nullable=True))
        batch_op.add_column(sa.Column('services_data', sa.Text(), nullable=True))
        
        # Journey & Facilities Sections fields
        batch_op.add_column(sa.Column('journey_heading', sa.String(300), nullable=True))
        batch_op.add_column(sa.Column('journey_items', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('journey_image', sa.String(300), nullable=True))
        
        batch_op.add_column(sa.Column('facilities_heading', sa.String(300), nullable=True))
        batch_op.add_column(sa.Column('facilities_cards', sa.Text(), nullable=True))
        
        # Why Patients Recommend fields
        batch_op.add_column(sa.Column('recommend_heading', sa.String(300), nullable=True))
        batch_op.add_column(sa.Column('recommend_items', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recommend_image', sa.String(300), nullable=True))
        
        # Advanced Care Section fields
        batch_op.add_column(sa.Column('advanced_heading', sa.String(300), nullable=True))
        batch_op.add_column(sa.Column('advanced_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('advanced_image', sa.String(300), nullable=True))
        
        # CTA Section fields
        batch_op.add_column(sa.Column('cta_heading', sa.String(300), nullable=True))
        batch_op.add_column(sa.Column('cta_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cta_phone', sa.String(20), nullable=True))
        
        batch_op.add_column(sa.Column('faq_content ', sa.Text(), nullable=True))
        
        # Add updated_at field
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_new', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('faq_content')
        batch_op.drop_column('cta_phone')
        batch_op.drop_column('cta_content')
        batch_op.drop_column('cta_heading')
        batch_op.drop_column('advanced_image')
        batch_op.drop_column('advanced_content')
        batch_op.drop_column('advanced_heading')
        batch_op.drop_column('recommend_image')
        batch_op.drop_column('recommend_items')
        batch_op.drop_column('recommend_heading')
        batch_op.drop_column('facilities_cards')
        batch_op.drop_column('facilities_heading')
        batch_op.drop_column('journey_image')
        batch_op.drop_column('journey_items')
        batch_op.drop_column('journey_heading')
        batch_op.drop_column('services_data')
        batch_op.drop_column('services_heading')
        batch_op.drop_column('approach_cards')
        batch_op.drop_column('approach_subheading')
        batch_op.drop_column('approach_heading')
        batch_op.drop_column('why_choose_title')
        batch_op.drop_column('why_choose_items')
        batch_op.drop_column('overview_content')
        batch_op.drop_column('overview_heading')
        batch_op.drop_column('hero_stats')
        batch_op.drop_column('hero_phone')
        batch_op.drop_column('hero_description')
        batch_op.drop_column('hero_main_heading')
         

    # ### end Alembic commands ###
