"""convert string to text for html support

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2025-03-16 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_new', schema=None) as batch_op:
        batch_op.alter_column('hero_main_heading',
                              existing_type=sa.String(500),
                              type_=sa.Text(),
                              existing_nullable=True)
        batch_op.alter_column('overview_heading',
                              existing_type=sa.String(300),
                              type_=sa.Text(),
                              existing_nullable=True)
        batch_op.alter_column('why_choose_title',
                              existing_type=sa.String(300),
                              type_=sa.Text(),
                              existing_nullable=True)
        batch_op.alter_column('approach_heading',
                              existing_type=sa.String(300),
                              type_=sa.Text(),
                              existing_nullable=True)
        batch_op.alter_column('services_heading',
                              existing_type=sa.String(300),
                              type_=sa.Text(),
                              existing_nullable=True)
        batch_op.alter_column('specialists_heading',
                              existing_type=sa.String(300),
                              type_=sa.Text(),
                              existing_nullable=True)
        batch_op.alter_column('journey_heading',
                              existing_type=sa.String(300),
                              type_=sa.Text(),
                              existing_nullable=True)
        batch_op.alter_column('facilities_heading',
                              existing_type=sa.String(300),
                              type_=sa.Text(),
                              existing_nullable=True)
        batch_op.alter_column('recommend_heading',
                              existing_type=sa.String(300),
                              type_=sa.Text(),
                              existing_nullable=True)
        batch_op.alter_column('advanced_heading',
                              existing_type=sa.String(300),
                              type_=sa.Text(),
                              existing_nullable=True)
        batch_op.alter_column('cta_heading',
                              existing_type=sa.String(300),
                              type_=sa.Text(),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_new', schema=None) as batch_op:
        batch_op.alter_column('cta_heading',
                              existing_type=sa.Text(),
                              type_=sa.String(300),
                              existing_nullable=True)
        batch_op.alter_column('advanced_heading',
                              existing_type=sa.Text(),
                              type_=sa.String(300),
                              existing_nullable=True)
        batch_op.alter_column('recommend_heading',
                              existing_type=sa.Text(),
                              type_=sa.String(300),
                              existing_nullable=True)
        batch_op.alter_column('facilities_heading',
                              existing_type=sa.Text(),
                              type_=sa.String(300),
                              existing_nullable=True)
        batch_op.alter_column('journey_heading',
                              existing_type=sa.Text(),
                              type_=sa.String(300),
                              existing_nullable=True)
        batch_op.alter_column('specialists_heading',
                              existing_type=sa.Text(),
                              type_=sa.String(300),
                              existing_nullable=True)
        batch_op.alter_column('services_heading',
                              existing_type=sa.Text(),
                              type_=sa.String(300),
                              existing_nullable=True)
        batch_op.alter_column('approach_heading',
                              existing_type=sa.Text(),
                              type_=sa.String(300),
                              existing_nullable=True)
        batch_op.alter_column('overview_heading',
                              existing_type=sa.Text(),
                              type_=sa.String(300),
                              existing_nullable=True)
        batch_op.alter_column('hero_main_heading',
                              existing_type=sa.Text(),
                              type_=sa.String(500),
                              existing_nullable=True)

    # ### end Alembic commands ###
