"""Add overview & services to Department

Revision ID: b762257716c8
Revises: 95ba77634c18
Create Date: 2025-09-13 15:33:15.581983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b762257716c8'
down_revision = '95ba77634c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overview_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('overview_quote', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('overview_quote_author', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('services', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('services')
        batch_op.drop_column('overview_quote_author')
        batch_op.drop_column('overview_quote')
        batch_op.drop_column('overview_content')

    # ### end Alembic commands ###
