"""Add alt_text to Banner

Revision ID: c1717c5dfc30
Revises: 5e2e5ba22584
Create Date: 2025-11-13 11:24:38.423994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1717c5dfc30'
down_revision = '5e2e5ba22584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('button_text', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('button_link', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.drop_column('button_link')
        batch_op.drop_column('button_text')

    # ### end Alembic commands ###
