"""Drop Specialist table

Revision ID: e2b38563a376
Revises: 01659e1c4d6a
Create Date: 2025-09-13 12:55:17.521238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b38563a376'
down_revision = '01659e1c4d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=150), nullable=False),
    sa.Column('designation', sa.VARCHAR(length=200), nullable=True),
    sa.Column('languages', sa.VARCHAR(length=250), nullable=True),
    sa.Column('consultation', sa.TEXT(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###
