"""Add SEO fields to Blog

Revision ID: f075fc41d646
Revises: 4368defe1c3d
Create Date: 2025-11-18 12:13:05.489604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f075fc41d646'
down_revision = '4368defe1c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('canonical_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('canonical_url')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')

    # ### end Alembic commands ###
