"""Remove User and UserAccess tables

Revision ID: f131bb78f73a
Revises: 3b00d38ea650
Create Date: 2025-09-15 12:23:03.587739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f131bb78f73a'
down_revision = '3b00d38ea650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_access')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_access',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('banners', sa.BOOLEAN(), nullable=True),
    sa.Column('doctors', sa.BOOLEAN(), nullable=True),
    sa.Column('counters', sa.BOOLEAN(), nullable=True),
    sa.Column('testimonials', sa.BOOLEAN(), nullable=True),
    sa.Column('specialities', sa.BOOLEAN(), nullable=True),
    sa.Column('departments', sa.BOOLEAN(), nullable=True),
    sa.Column('health_packages', sa.BOOLEAN(), nullable=True),
    sa.Column('sports_packages', sa.BOOLEAN(), nullable=True),
    sa.Column('department_content', sa.BOOLEAN(), nullable=True),
    sa.Column('users', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('emp_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('emp_id')
    )
    # ### end Alembic commands ###
