"""Replace detailed time fields with single timings column

Revision ID: f2cd24ea4ee3
Revises: 22f866fb10f0
Create Date: 2025-09-16 15:06:11.976936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2cd24ea4ee3'
down_revision = '22f866fb10f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timings', sa.String(length=300), nullable=True))
        batch_op.drop_column('time_from_ampm')
        batch_op.drop_column('day_to')
        batch_op.drop_column('time_to_hour')
        batch_op.drop_column('time_from_hour')
        batch_op.drop_column('time_from_min')
        batch_op.drop_column('day_from')
        batch_op.drop_column('time_to_min')
        batch_op.drop_column('time_to_ampm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_to_ampm', sa.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('time_to_min', sa.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('day_from', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('time_from_min', sa.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('time_from_hour', sa.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('time_to_hour', sa.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('day_to', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('time_from_ampm', sa.VARCHAR(length=2), nullable=True))
        batch_op.drop_column('timings')

    # ### end Alembic commands ###
