"""Add primary and secondary doctor links to LifeMoment

Revision ID: fff293978b17
Revises: 307e1356001d
Create Date: 2025-12-12 17:15:16.157349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff293978b17'
down_revision = '307e1356001d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('life_moments', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('doctor1_id', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column('doctor2_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_life_moments_doctor1', 'doctors', ['doctor1_id'], ['id'])
        batch_op.create_foreign_key(
            'fk_life_moments_doctor2', 'doctors', ['doctor2_id'], ['id'])
        batch_op.drop_column('doctor_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('life_moments', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('doctor_name', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('doctor2_id')
        batch_op.drop_column('doctor1_id')

    # ### end Alembic commands ###
